import type { Metadata } from "next";
import { Inter } from "next/font/google";

import {
  QueryClient,
  QueryClientProvider,
} from '@tanstack/react-query'

import "./globals.css";
import { ReactQueryClientProvider } from "@/components/ReactQueryClientProvider";

const queryClient = new QueryClient()
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ReactQueryClientProvider>
      <html lang="en">
        <body className={inter.className}>
            {children}
        </body>
      </html>
    </ReactQueryClientProvider>
  );
}
